export const LOADING_PENDING = 'LOADING_PENDING';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const HANDLE_SHOW_MODAL = 'HANDLE_SHOW_MODAL';
export const HANDLE_CLOSE_MODAL = 'HANDLE_CLOSE_MODAL';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_USER = 'SET_USER';
