//Application
export const LOADING_PENDING = 'LOADING_PENDING';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const HANDLE_SHOW_NOTIFICATION_MODAL = 'HANDLE_SHOW_NOTIFICATION_MODAL';
export const HANDLE_CLOSE_NOTIFICATION_MODAL = 'HANDLE_CLOSE_NOTIFICATION_MODAL';
export const HANDLE_SHOW_ACTION_MODAL = 'HANDLE_SHOW_ACTION_MODAL';
export const HANDLE_CLOSE_ACTION_MODAL = 'HANDLE_CLOSE_ACTION_MODAL';

//Authentication
export const GET_AUTH_STATUS_PENDING = 'GET_AUTH_STATUS_PENDING';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//User
export const SET_USER = 'SET_USER';

//Projects
export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';
export const CREATE_NEW_PROJECT_PENDING = 'CREATE_NEW_PROJECT_PENDING';
export const CREATE_NEW_PROJECT_SUCCESS = 'CREATE_NEW_PROJECT_SUCCESS';
export const CREATE_NEW_PROJECT_FAILURE = 'CREATE_NEW_PROJECT_FAILURE';
export const DELETE_PROJECT_PENDING = 'DELETE_PROJECT_PENDING';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';
export const GET_PROJECT_PENDING = 'GET_PROJECT_PENDING';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = 'GET_PROJECT_FAILURE';
