name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

        run: |
          git config --global user.name 'Aleh Barushka'
          git config --global user.email '1.AlehBarushka@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
